#!/usr/bin/env python3
# Ok this is very silly but pdbrc is read by pdb as a series of pdb commands.
# This means we can only use python one-liners as pdb doesn't understand
# multi-line commands
from contextlib import suppress

with suppress(ImportError): import gnureadline
with suppress(ImportError): import readline

import rlcompleter
pdb.Pdb.complete = rlcompleter.Completer(locals()).complete
