#!/usr/bin/env python3
# Ok this is very silly but pdbrc is read by pdb as a series of pdb commands.
# This means we can only use python one-liners as pdb doesn't understand
# multi-line commands
from contextlib import suppress

with suppress(ImportError): import gnureadline
with suppress(ImportError): import readline

with suppress(NameError): gnureadline.parse_and_bind('tab: complete')
with suppress(NameError): readline.parse_and_bind('tab: complete')

import rlcompleter
pdb_completer = rlcompleter.Completer(locals()).complete
pdb.Pdb.complete = pdb_completer
with suppress(NameError): gnureadline.set_completer(pdb_completer)
