#!/usr/bin/env python
import os
import atexit

try:
    import gnureadline
except ImportError:
    import readline

import rlcompleter

if 'libedit' in readline.__doc__:
    readline.parse_and_bind("bind ^I rl_complete")
else:
    readline.parse_and_bind("tab: complete")

HISTFILE="{}/.pyhistory".format(os.environ["HOME"])

# Read the existing history if there is one
try:
    if os.path.exists(HISTFILE):
        readline.read_history_file(HISTFILE)
except IOError:
    pass

# Set maximum number of items that will be written to the history file
readline.set_history_length(300)

def savehist():
    readline.write_history_file(HISTFILE)

atexit.register(savehist)
